### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by henrydatei** [ScoreSaber/scoresaber-plugin#15]
I just cloned the repo and wanted to compile it but I'm getting a hole bunch of errors
| Severity | Code   | Description                                                                                                                       | Project    | File                                                                                                                                                      | Line | Suppression State |
|----------|--------|-----------------------------------------------------------------------------------------------------------------------------------|------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|------|-------------------|
| Error    | CS0246 | The type or namespace name 'TimeTweeningManager' could not be found (are you missing a using directive or an assembly reference?) | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 144  | Active            |
| Error    | CS0246 | The type or namespace name 'Tween' could not be found (are you missing a using directive or an assembly reference?)               | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 95   | Active            |
| Error    | CS0246 | The type or namespace name 'TimeTweeningManager' could not be found (are you missing a using directive or an assembly reference?) | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 105  | Active            |
| Error    | CS0117 | 'PauseController' does not contain a definition for 'HandleHMDUnmounted'                                                          | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\HarmonyPatches\AntiInterrupt.cs                       | 5    | Active            |
| Error    | CS0122 | 'ScoreController.LateUpdate()' is inaccessible due to its protection level                                                        | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\HarmonyPatches\CancelScoreControllerBufferFinisher.cs | 24   | Active            |
| Error    | CS0117 | 'NoteCutSoundEffectManager' does not contain a definition for 'HandleNoteWasSpawned'                                              | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\HarmonyPatches\CutSoundEffectOverride.cs              | 8    | Active            |
| Error    | CS0117 | 'RelativeScoreAndImmediateRankCounter' does not contain a definition for 'UpdateRelativeScoreAndImmediateRank'                    | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\HarmonyPatches\ImmediateRankReinitializer.cs          | 6    | Active            |
| Error    | CS0117 | 'ScoreController' does not contain a definition for 'HandleNoteWasCut'                                                            | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 19   | Active            |
| Error    | CS0117 | 'ScoreController' does not contain a definition for 'HandleNoteWasMissed'                                                         | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 31   | Active            |
| Error    | CS0117 | 'MissedNoteEffectSpawner' does not contain a definition for 'HandleNoteWasMissed'                                                 | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 45   | Active            |
| Error    | CS0117 | 'BombNoteController' does not contain a definition for 'HandleWasCutBySaber'                                                      | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 69   | Active            |
| Error    | CS0117 | 'ScoreUIController' does not contain a definition for 'HandleScoreDidChangeRealtime'                                              | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 81   | Active            |
| Error    | CS0117 | 'RelativeScoreAndImmediateRankCounter' does not contain a definition for 'HandleScoreDidChange'                                   | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 91   | Active            |
| Error    | CS0117 | 'StandardLevelGameplayManager' does not contain a definition for 'HandleGameEnergyDidReach0'                                      | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Legacy\LegacyReplayPatches.cs                         | 101  | Active            |
| Error    | CS0117 | 'ScoreController' does not contain a definition for 'HandleNoteWasCut'                                                            | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\Recorders\NoteEventRecorder.cs                        | 118  | Active            |
| Error    | CS0246 | The type or namespace name 'TimeTweeningManager' could not be found (are you missing a using directive or an assembly reference?) | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\UI\SpectateAreaController.cs                          | 13   | Active            |
| Error    | CS0246 | The type or namespace name 'Tween' could not be found (are you missing a using directive or an assembly reference?)               | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\UI\SpectateAreaController.cs                          | 19   | Active            |
| Error    | CS0246 | The type or namespace name 'Tween' could not be found (are you missing a using directive or an assembly reference?)               | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\UI\SpectateAreaController.cs                          | 20   | Active            |
| Error    | CS0246 | The type or namespace name 'TimeTweeningManager' could not be found (are you missing a using directive or an assembly reference?) | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Core\ReplaySystem\UI\SpectateAreaController.cs                          | 23   | Active            |
| Error    | CS0117 | 'PlatformLeaderboardViewController' does not contain a definition for 'Refresh'                                                   | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\Patches\LeaderboardPatches.cs                                           | 29   | Active            |
| Error    | CS0246 | The type or namespace name 'FloatTween' could not be found (are you missing a using directive or an assembly reference?)          | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 307  | Active            |
| Error    | CS0103 | The name 'EaseType' does not exist in the current context                                                                         | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 307  | Active            |
| Error    | CS0103 | The name 'EaseType' does not exist in the current context                                                                         | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 307  | Active            |
| Error    | CS0246 | The type or namespace name 'FloatTween' could not be found (are you missing a using directive or an assembly reference?)          | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 323  | Active            |
| Error    | CS0103 | The name 'EaseType' does not exist in the current context                                                                         | ScoreSaber | C:\Users\henry\Downloads\scoresaber-plugin-main\scoresaber-plugin-main\ScoreSaber\UI\Leaderboard\PanelView.cs                                             | 323  | Active            |

I'm using Visual Studio with BeatsaberModdingTools.

I'm relatively new to C# so please forgive any stupid questions! Thanks

**Comment by Qwasyx** [comment]
This is caused by modding changes on the new game versions. I already have the adjusted files laying around, but want to resolve one last question on those before pushing them to the repository.
