### ISSUE TITLE
Unable to log in, auth token

### ISSUE THREAD

**Issue by z3t4m4n** [ScoreSaber/scoresaber-plugin#3]
Hi, 
When I open BS and select a custom level I see the following on the scoreboard:
"Failed to authenticate with scoresaber! Please restart your game" 
I've restarted the game several times, validated it, uninstalled all the mods, run BS, install just the essential mods for scoresaber, no joy.
I see the following on the logs:
```
[DEBUG @ 21:35:53 | ScoreSaber] Signing into ScoreSaber...
[ERROR @ 21:35:54 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 21:35:54 | ScoreSaber] Failed, attempting again (1 of 3 tries...)
[ERROR @ 21:35:58 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 21:35:58 | ScoreSaber] Failed, attempting again (2 of 3 tries...)
[ERROR @ 21:36:02 | ScoreSaber] Failed user authentication: Exception of type '#=znWVbbj8I0237C7iWHHW3$1Q=' was thrown.
[DEBUG @ 21:36:02 | ScoreSaber] Failed, attempting again (3 of 3 tries...)
[DEBUG @ 21:36:06 | ScoreSaber] Failed to authenticate with ScoreSaber! Please restart your game
```

Thanks.
[2022.11.14.21.35.36.log](https://github.com/ScoreSaber/ScoreSaber-Plugin/files/10070068/2022.11.14.21.35.36.log)

P.S.: Initially oppened as https://github.com/ScoreSaber/ScoreSaber-Frontend/issues/80

**Comment by Loloppe** [comment]
It is fixed in the latest version according to Umbranox, but need to wait for a new release.

**Comment by Umbranoxio** [comment]
This is now fixed in the latest release.
