### ISSUE TITLE
Score Failed to upload

### ISSUE THREAD

**Issue by ghost** [ScoreSaber/scoresaber-plugin#6]
my score fail to upload after i play a song

-     Game version: 1.26
-     Plugin version: v3.2.13
-     Platform: Steam
[_latest.log](https://github.com/ScoreSaber/ScoreSaber-Plugin/files/10295712/_latest.log)

**Comment by Qwasyx** [comment]
This seems to be a general issue with this plugin version and 1.26. If you update to 1.27 that should fix the issue

**Comment by ghost** [comment]
I have updated.
And not tested yet but i will close the issue for now until further notice.
Edit: 1.27 is working fine
